--------------------------------------------------------
--  File created - пятница-мая-17-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VACANCIES
--------------------------------------------------------

  CREATE TABLE "SYS"."VACANCIES" 
   (	"VACANCYID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITLE" VARCHAR2(100 BYTE), 
	"REQUIREMENTS" VARCHAR2(100 BYTE), 
	"CONDITIONS" VARCHAR2(100 BYTE), 
	"SALARY" NUMBER, 
	"PUBLICATIONDATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.VACANCIES
SET DEFINE OFF;
Insert into SYS.VACANCIES (VACANCYID,TITLE,REQUIREMENTS,CONDITIONS,SALARY,PUBLICATIONDATE) values ('1','Разработчик ПО','Высшее техническое образование, опыт работы от 2 лет','Офисная работа, гибкий график','100000',to_date('15.03.24','DD.MM.RR'));
Insert into SYS.VACANCIES (VACANCYID,TITLE,REQUIREMENTS,CONDITIONS,SALARY,PUBLICATIONDATE) values ('4','UX/UI дизайнер','Опыт работы от 2 лет, знание инструментов дизайна','Гибкий график','90000',to_date('14.03.24','DD.MM.RR'));
Insert into SYS.VACANCIES (VACANCYID,TITLE,REQUIREMENTS,CONDITIONS,SALARY,PUBLICATIONDATE) values ('7','Финансовый аналитик','Высшее экономическое образование, опыт работы от 3 лет','Офисная работа','130000',to_date('15.03.24','DD.MM.RR'));
Insert into SYS.VACANCIES (VACANCYID,TITLE,REQUIREMENTS,CONDITIONS,SALARY,PUBLICATIONDATE) values ('12','Специалист по технической поддержке','Опыт работы в IT-поддержке от 1 года, коммуникабельность','Офисная работа','85000',to_date('14.03.24','DD.MM.RR'));
Insert into SYS.VACANCIES (VACANCYID,TITLE,REQUIREMENTS,CONDITIONS,SALARY,PUBLICATIONDATE) values ('15','Web-разработчик','Опыт веб-разработки от 2 лет, знание HTML, CSS, JavaScript','Гибкий график','100000',to_date('15.03.24','DD.MM.RR'));
Insert into SYS.VACANCIES (VACANCYID,TITLE,REQUIREMENTS,CONDITIONS,SALARY,PUBLICATIONDATE) values ('17','Тестировщик ПО','Опыт тестирования от 1 года','Удаленная работа','80000',to_date('14.03.24','DD.MM.RR'));
--------------------------------------------------------
--  DDL for Index PK_VACANCIES
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."PK_VACANCIES" ON "SYS"."VACANCIES" ("VACANCYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VACANCIES
--------------------------------------------------------

  ALTER TABLE "SYS"."VACANCIES" MODIFY ("VACANCYID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."VACANCIES" ADD CONSTRAINT "PK_VACANCIES" PRIMARY KEY ("VACANCYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
