CREATE TABLESPACE lob_tablespace
DATAFILE 'lob_datafile.dbf'
SIZE 100M
AUTOEXTEND ON
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;


CREATE USER c##lob_user IDENTIFIED BY password;
GRANT CONNECT, RESOURCE TO c##lob_user;
GRANT CREATE SESSION TO c##lob_user;
GRANT UNLIMITED TABLESPACE TO c##lob_user;


ALTER USER c##lob_user QUOTA UNLIMITED ON lob_tablespace;



CREATE TABLE lob_tb (
    CCC CLOB,
    FOTO BLOB,
    DOC BFILE
);

DROP TABLE lob_tb;

DROP DIRECTORY LOBDIR;
CREATE DIRECTORY LOBDIR AS 'C:\LOBDIR';


INSERT INTO lob_tb VALUES ('HELLO WORLD', NULL, NULL);

INSERT INTO lob_tb VALUES (NULL, NULL, BFILENAME('LOBDIR', 'xx.pdf'));

INSERT INTO lob_tb VALUES (NULL, BFILENAME('LOBDIR', 'xxx.jpg'), NULL);

select * from lob_tb;

